language: python
python:
            - '3.8'

install:
            - pip install -r requirements-dev.txt

env:
            - PYTHONPATH=/home/travis/build/jimenacotera/repototestwhatiswrong

script:
            - make tests

deploy:
            - provider: heroku
              api_key: $HEROKU_API_KEY
              app: demo-repo22
              on:
                branch: master
