language: python
python:
            - '3.8'

install:
            - pip install -r requirements-dev.txt

env:
            - PYTHONPATH=/home/travis/build/gcallah/demo-repo2

script:
            - make tests
